services:

  mysql:
    image: mysql:8.4
    container_name: entidades-mysql
    environment:
      MYSQL_ROOT_PASSWORD: entidades123
      MYSQL_DATABASE: entidades
    ports:
      - "3307:3306"
    volumes:
      - ./entidades.sql:/docker-entrypoint-initdb.d/entidades.sql:ro

  app:
    build: .
    container_name: entidades-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
